### ISSUE TITLE
Gallery Submission Feedback

### ISSUE THREAD

**Issue by julianhsu8** [Billy-Grace/billypix-web-event-tag#1]
When reviewing your template, we found that it does not properly parse.  Perhaps there is a typo, e.g. a ] where a  } should be.

**Comment by vascograce** [comment]
@julianhsu8  Thanks for the quick feedback, I just updated the code. Could you check again?

**Comment by julianhsu8** [comment]
Still seeing

SyntaxError: Unexpected token ']', ..."YTICS",
],
"bran"... is not valid JSON

**Comment by vascograce** [comment]
Alright so the SHA in the `metadata.yaml` was not updated to match the commit that fixed the issue, I updated this file on all our 3 repos. I really hope this finally fixes the issue🤞
